DROP DATABASE IF EXISTS AJEDREZ;
CREATE DATABASE IF NOT EXISTS AJEDREZ;
USE AJEDREZ;

CREATE TABLE PAISES(
    COD_PAIS INT UNSIGNED PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    N_CLUBS TINYINT UNSIGNED
);

CREATE TABLE PARTICIPANTES(
    COD_PARTICIPANTE INT UNSIGNED PRIMARY KEY,
    N_ASOCIADO VARCHAR(100),
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(150),
    TLF VARCHAR(20),
    COD_PAIS INT UNSIGNED NOT NULL,
    TIPO CHAR(1) NOT NULL CHECK (TIPO IN ('J','A')),
    CONSTRAINT FK_COD_PAIS_PARTICIPANTES_PAISES 
        FOREIGN KEY(COD_PAIS) REFERENCES PAISES(COD_PAIS) 
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE JUGADORES(
    COD_PARTICIPANTE INT UNSIGNED PRIMARY KEY,
    NIVEL_JUEGO TINYINT UNSIGNED NOT NULL CHECK(NIVEL_JUEGO BETWEEN 1 AND 10),
    CONSTRAINT FK_COD_PARTICIPANTE_JUGADORES_PARTICIPANTES 
        FOREIGN KEY(COD_PARTICIPANTE) REFERENCES PARTICIPANTES(COD_PARTICIPANTE) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ARBITROS(
    COD_PARTICIPANTE INT UNSIGNED PRIMARY KEY,
    CONSTRAINT FK_COD_PARTICIPANTE_ARBITROS_PARTICIPANTES 
        FOREIGN KEY(COD_PARTICIPANTE) REFERENCES PARTICIPANTES(COD_PARTICIPANTE) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE HOTELES(
    COD_HOTEL INT UNSIGNED PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(150),
    TLF VARCHAR(20)
);

CREATE TABLE SALAS(
    COD_SALA INT UNSIGNED PRIMARY KEY,
    CAPACIDAD TINYINT UNSIGNED NOT NULL,
    COD_HOTEL INT UNSIGNED NOT NULL,
    CONSTRAINT FK_COD_HOTEL_SALAS_HOTELES 
        FOREIGN KEY(COD_HOTEL) REFERENCES HOTELES(COD_HOTEL) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE MEDIOS(
    COD_SALA INT UNSIGNED,
    MEDIO VARCHAR(100) NOT NULL,
    PRIMARY KEY(COD_SALA, MEDIO),
    CONSTRAINT FK_COD_SALA_MEDIOS_SALAS 
        FOREIGN KEY(COD_SALA) REFERENCES SALAS(COD_SALA) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SE_ALOJAN(
    COD_PARTICIPANTE INT UNSIGNED,
    COD_HOTEL INT UNSIGNED,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NULL,
    PRIMARY KEY(COD_PARTICIPANTE, COD_HOTEL, FECHA_INICIO),
    CONSTRAINT FK_COD_PARTICIPANTE_SEALOJAN_PARTICIPANTES 
        FOREIGN KEY(COD_PARTICIPANTE) REFERENCES PARTICIPANTES(COD_PARTICIPANTE) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_COD_HOTEL_SEALOJAN_HOTELES 
        FOREIGN KEY(COD_HOTEL) REFERENCES HOTELES(COD_HOTEL) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CAMPEONATOS(
    COD_PARTICIPANTE INT UNSIGNED,
    CAMPEONATO VARCHAR(100) NOT NULL,
    PRIMARY KEY(COD_PARTICIPANTE, CAMPEONATO),
    CONSTRAINT FK_COD_PARTICIPANTE_CAMPEONATOS_PARTICIPANTES 
        FOREIGN KEY(COD_PARTICIPANTE) REFERENCES PARTICIPANTES(COD_PARTICIPANTE) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PUEDE_REPRESENTAR(
    COD_PAIS_REPRESENTA INT UNSIGNED,
    COD_PAIS_REPRESENTADO INT UNSIGNED,
    PRIMARY KEY(COD_PAIS_REPRESENTA, COD_PAIS_REPRESENTADO),
    CONSTRAINT FK_COD_PAIS_REPRESENTA_PUEDE_REPRESENTAR_PAISES 
        FOREIGN KEY(COD_PAIS_REPRESENTA) REFERENCES PAISES(COD_PAIS) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_COD_PAIS_REPRESENTADO_PUEDE_REPRESENTAR_PAISES 
        FOREIGN KEY(COD_PAIS_REPRESENTADO) REFERENCES PAISES(COD_PAIS) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE JORNADAS(
    COD_JORNADA INT UNSIGNED PRIMARY KEY,
    N_JORNADA TINYINT UNSIGNED NOT NULL,
    FECHA DATE NOT NULL
);

-- AQUÍ ESTABA EL ERROR: se elimina COD_PARTICIPANTE y su FK
CREATE TABLE PARTIDAS(
    COD_PARTIDA INT UNSIGNED PRIMARY KEY,
    COD_JORNADA INT UNSIGNED NOT NULL,
    COD_SALA INT UNSIGNED NOT NULL,
    N_ENTRADAS_VENDIDAS TINYINT UNSIGNED NOT NULL,
    CONSTRAINT FK_COD_JORNADA_PARTIDAS_JORNADAS 
        FOREIGN KEY(COD_JORNADA) REFERENCES JORNADAS(COD_JORNADA) 
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_COD_SALA_PARTIDAS_SALAS 
        FOREIGN KEY(COD_SALA) REFERENCES SALAS(COD_SALA) 
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE MOVIMIENTOS(
    COD_PARTIDA INT UNSIGNED,
    N_MOVIMIENTO TINYINT UNSIGNED,
    COMENTARIO TEXT,
    POSICION1 TINYINT UNSIGNED NULL,
    POSICION2 TINYINT UNSIGNED NULL,
    POSICION3 TINYINT UNSIGNED NULL,
    POSICION4 TINYINT UNSIGNED NULL,
    POSICION5 TINYINT UNSIGNED NULL,
    PRIMARY KEY(COD_PARTIDA, N_MOVIMIENTO),
    CONSTRAINT FK_COD_PARTIDA_MOVIMIENTOS_PARTIDAS 
        FOREIGN KEY(COD_PARTIDA) REFERENCES PARTIDAS(COD_PARTIDA) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE JUEGAN(
    COD_PARTICIPANTE INT UNSIGNED,
    COD_PARTIDA INT UNSIGNED,
    COLOR VARCHAR(20) NOT NULL,
    PRIMARY KEY(COD_PARTICIPANTE, COD_PARTIDA),
    CONSTRAINT FK_COD_PARTICIPANTE_JUEGAN_PARTICIPANTES 
        FOREIGN KEY(COD_PARTICIPANTE) REFERENCES PARTICIPANTES(COD_PARTICIPANTE) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_COD_PARTIDA_JUEGAN_PARTIDAS 
        FOREIGN KEY(COD_PARTIDA) REFERENCES PARTIDAS(COD_PARTIDA) 
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE GANAN(
    COD_PARTICIPANTE INT UNSIGNED,
    COD_PARTIDA INT UNSIGNED,
    PRIMARY KEY(COD_PARTICIPANTE, COD_PARTIDA),
    CONSTRAINT FK_COD_PARTICIPANTE_GANAN_PARTICIPANTES 
        FOREIGN KEY(COD_PARTICIPANTE) REFERENCES PARTICIPANTES(COD_PARTICIPANTE) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_COD_PARTIDA_GANAN_PARTIDAS 
        FOREIGN KEY(COD_PARTIDA) REFERENCES PARTIDAS(COD_PARTIDA) 
        ON UPDATE CASCADE ON DELETE CASCADE
);