DROP DATABASE IF EXISTS BD_TEORIA_DML;
CREATE DATABASE IF NOT EXISTS BD_TEORIA_DML;
USE BD_TEORIA_DML;

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS(
DEP_NO INT(11) AUTO_INCREMENT PRIMARY KEY,
DNOMBRE VARCHAR(25) NOT NULL,
LOCALIDAD VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTOS(
PRODUCTO_NO INT(11) PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL,
PRECIO_ACTUAL DECIMAL(9,2) UNSIGNED NOT NULL,
STOCK_DISPONIBLE INT(25) UNSIGNED NOT NULL

);

CREATE TABLE IF NOT EXISTS EMPLEADOS(
EMP_NO INT(11) PRIMARY KEY,
APELLIDO VARCHAR(25) NOT NULL,
OFICIO VARCHAR(25) NOT NULL,
DIRECTOR INT(11) NULL,
FECHA_ALTA DATE NOT NULL,
SALARIO DECIMAL(9,2) NOT NULL,
COMISION DECIMAL(9,2),
DEP_NO INT(11) NOT NULL,

CONSTRAINT FK_DEP_NO_EMPLEADOS_DEPARTAMENTOS FOREIGN KEY(DEP_NO) REFERENCES DEPARTAMENTOS(DEP_NO) ON UPDATE CASCADE ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS CLIENTES(
CLIENTE_NO INT(11) PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
LOCALIDAD VARCHAR(25) NOT NULL,
VENDEDOR_NO INT(25) NULL,
DEBE DECIMAL(9,2) NOT NULL DEFAULT 0.00,
HABER DECIMAL(9,2) NOT NULL DEFAULT 0.00,
LIMITE_CREDITO DECIMAL(9,2) NOT NULL,

CONSTRAINT FK_VENDEDOR_NO_CLIENTES_EMPLEADOS FOREIGN KEY(VENDEDOR_NO) REFERENCES EMPLEADOS(EMP_NO) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PEDIDOS(
PEDIDO_NO INT(11) PRIMARY KEY,
PRODUCTO_NO INT(25),
CLIENTE_NO INT(25),
UNIDADES INT(25) UNSIGNED NOT NULL,
FECHA_PEDIDO DATE NOT NULL,

CONSTRAINT FK_PRODUCTO_NO_PEDIDOS_PRODUCTOS FOREIGN KEY(PRODUCTO_NO) REFERENCES PRODUCTOS(PRODUCTO_NO) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_CLIENTE_NO_PEDIDOS_CLIENTES FOREIGN KEY(CLIENTE_NO) REFERENCES CLIENTES(CLIENTE_NO) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_DIRECTOR_EMPLEADOS_EMPLEADOS FOREIGN KEY(DIRECTOR) REFERENCES EMPLEADOS(EMP_NO) ON UPDATE CASCADE ON DELETE SET NULL;