DROP DATABASE IF EXISTS 00_AUTOBUSES;
CREATE DATABASE IF NOT EXISTS 00_AUTOBUSES;
USE 00_AUTOBUSES;

CREATE TABLE IF NOT EXISTS CLIENTES(
COD_CLIENTE INT(11) AUTO_INCREMENT PRIMARY KEY,
DNI CHAR(9) NOT NULL UNIQUE,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO_1 VARCHAR(150) NOT NULL,
APELLIDO_2 VARCHAR(150) NULL,
DIRECCION VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVAS(
COD_RESERVA INT(11) AUTO_INCREMENT PRIMARY KEY,
LOCALIZADOR CHAR(20) NOT NULL UNIQUE,
FECHA DATE NOT NULL,
COD_CLIENTE INT(11) NOT NULL,
    
CONSTRAINT FK_COD_CLIENTE_RESERVAS_CLIENTES FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AUTOBUSES(
COD_AUTOBUS INT(11) AUTO_INCREMENT PRIMARY KEY,
MATRICULA CHAR(7) NOT NULL UNIQUE,
NUM_BASTIDOR VARCHAR(25) NOT NULL UNIQUE,
ALTO DECIMAL(7,2) UNSIGNED NOT NULL,
ANCHO DECIMAL(7,2) UNSIGNED NULL,
LARGO DECIMAL(7,2) UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS ASIENTOS_AUTOBUS(
NUM_ASIENTO TINYINT DEFAULT 55,
COD_AUTOBUS INT(11) NOT NULL,
VENTANA_PASILLO ENUM('SI','NO') NOT NULL,
PRIMARY KEY(NUM_ASIENTO, COD_AUTOBUS),

CONSTRAINT CHK_NUM_ASIENTO_ASIENTOS CHECK(NUM_ASIENTO IN (25,35,55)),
CONSTRAINT FK_COD_AUTOBUS_ASIENTOS_AUTOBUSES FOREIGN KEY(COD_AUTOBUS) REFERENCES AUTOBUSES(COD_AUTOBUS) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CODIGOS_POSTALES(
CP CHAR(5) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL,
PAIS VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCALIDADES(
COD_LOCALIDAD INT(11) AUTO_INCREMENT PRIMARY KEY,
CP CHAR(5) NOT NULL,
    
CONSTRAINT FK_CP_LOCALIDADES_CODIGOS_POSTALES FOREIGN KEY(CP) REFERENCES CODIGOS_POSTALES(CP) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RUTAS(
COD_RUTA INT(11) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
COD_LOCALIDAD_EMPIEZA INT(11) NOT NULL,
COD_LOCALIDAD_ACABA INT(11) NOT NULL,

CONSTRAINT FK_COD_LOCALIDAD_EMPIEZA_RUTAS_LOCALIDADES FOREIGN KEY(COD_LOCALIDAD_EMPIEZA) REFERENCES LOCALIDADES(COD_LOCALIDAD) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_COD_LOCALIDAD_ACABA_RUTAS_LOCALIDADES FOREIGN KEY(COD_LOCALIDAD_ACABA) REFERENCES LOCALIDADES(COD_LOCALIDAD) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PARADAS(
NUM_PARADA INT(11),
COD_RUTA INT(11),
NUM_ORDEN TINYINT UNSIGNED NOT NULL,
PRECIO_BILLETE DECIMAL(5,2) UNSIGNED NOT NULL,
LATITUD VARCHAR(30) NOT NULL,
LOGITUD VARCHAR(30) NOT NULL,
DIRECCION_COMPLETA VARCHAR(100) NOT NULL,
COD_LOCALIDAD INT(11) NOT NULL,

PRIMARY KEY(NUM_PARADA,COD_RUTA),

CONSTRAINT CHK_PRECIO_BILLETE_PARADAS CHECK(PRECIO_BILLETE <= 149.99),
CONSTRAINT FK_COD_LOCALIDAD_PARADAS_LOCALIDADES FOREIGN KEY(COD_LOCALIDAD) REFERENCES LOCALIDADES(COD_LOCALIDAD) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CONTIENE(
COD_RESERVA INT(11),
NUM_ASIENTO TINYINT,
COD_AUTOBUS INT(11),
NUM_PARADA INT(11),
COD_RUTA INT(11),

PRIMARY KEY(COD_RESERVA, NUM_ASIENTO, COD_AUTOBUS, NUM_PARADA, COD_RUTA),

CONSTRAINT FK_COD_RESERVA_CONTIENE_RESERVAS FOREIGN KEY(COD_RESERVA) REFERENCES RESERVAS(COD_RESERVA) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_NUM_ASIENTO_COD_AUTOBUS_CONTINE_ASIENTOS FOREIGN KEY(NUM_ASIENTO,COD_AUTOBUS) REFERENCES ASIENTOS_AUTOBUS(NUM_ASIENTO,COD_AUTOBUS) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_NUM_PARADA_COD_RUTA_CONTINE_PARADA FOREIGN KEY(NUM_PARADA, COD_RUTA) REFERENCES PARADAS(NUM_PARADA,COD_RUTA) ON UPDATE CASCADE ON DELETE CASCADE
);
