CREATE DATABASE IF NOT EXISTS MINI_EJEMPLO_EXAMEN CHARACTER SET UTF8;
USE MINI_EJEMPLO_EXAMEN;

CREATE TABLE IF NOT EXISTS CLIENTES(
COD_CLIENTE INT(11) AUTO_INCREMENT PRIMARY KEY,
NIF CHAR(9) UNIQUE,
NOMBRE VARCHAR(25) NOT NULL,
DIRECCION VARCHAR(150) NOT NULL,
CIUDAD VARCHAR(100) NOT NULL,
TELEFONO CHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS COCHES(
MATRICULA INT(11) AUTO_INCREMENT PRIMARY KEY,
MARCA VARCHAR(50) NOT NULL,
MODELO VARCHAR(150) NOT NULL,
PVP DECIMAL(5) UNSIGNED NOT NULL,
COD_CLIENTE INT(11),
CONSTRAINT FK_COD_CLIENTE_COCHES_CLIENTES FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REVISIONES(
COD_REVISION INT(11) AUTO_INCREMENT PRIMARY KEY,
FECHA DATE,
MATRICULA INT(11),
CONSTRAINT FK_MATRICULA_REVISIONES_COCHES FOREIGN KEY(MATRICULA) REFERENCES COCHES(MATRICULA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS OPERACIONES(
COD_OPERACION INT(11) AUTO_INCREMENT PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL,
HORAS CHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSTA(
COD_REVISION INT(11),
COD_OPERACION INT(11),
CONSTRAINT PK_CONSTA PRIMARY KEY(COD_REVISION, COD_OPERACION),
CONSTRAINT FK_COD_REVISION_CONSTA_REVISIONES FOREIGN KEY(COD_REVISION) REFERENCES REVISIONES(COD_REVISION) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_COD_OPERACION_CONSTA_OPERACIONES FOREIGN KEY(COD_OPERACION) REFERENCES OPERACIONES(COD_OPERACION) ON UPDATE CASCADE ON DELETE CASCADE
);
