DROP DATABASE IF EXISTS COCINA_IKEA;
CREATE DATABASE IF NOT EXISTS COCINA_IKEA;
USE COCINA_IKEA;

CREATE TABLE IF NOT EXISTS CLIENTES(
COD_CLIENTE INT(11) AUTO_INCREMENT PRIMARY KEY,
NIF CHAR(9) UNIQUE NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(200) NOT NULL,
TLF_FIJO CHAR(9),
TLF_MOVIL CHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS DISTRIBUIDORES(
COD_DISTRIBUIDOR INT(11) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS FABRICANTES(
COD_FABRICANTE INT(11) AUTO_INCREMENT PRIMARY KEY,
NIF CHAR(9) UNIQUE NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS MONTADORES(
COD_MONTADOR INT(11) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(200) NOT NULL,
TLF CHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS COCINAS(
COD_COCINA INT(11) AUTO_INCREMENT PRIMARY KEY,
COD_DISTRIBUIDOR INT(11) NOT NULL,
COD_CLIENTE INT(11) NOT NULL,
    
CONSTRAINT FK_COD_DISTRIBUIDOR_COCINAS FOREIGN KEY (COD_DISTRIBUIDOR) REFERENCES DISTRIBUIDORES(COD_DISTRIBUIDOR) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_COD_CLIENTE_COCINAS FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MUEBLES(
COD_MUEBLE INT(11) AUTO_INCREMENT PRIMARY KEY,
LINEA VARCHAR(25) NOT NULL,
COLOR VARCHAR(25) NOT NULL,
ALTO DECIMAL(3,2) UNSIGNED NOT NULL,
LARGO DECIMAL(3,2) UNSIGNED NOT NULL,
ANCHO DECIMAL(3,2) UNSIGNED NOT NULL,
TIPO_MUEBLE ENUM('A','B','P','E') NOT NULL,
COD_FABRICANTE INT(11) NOT NULL,
COD_COCINA INT(11) NOT NULL,
    
CONSTRAINT FK_COD_FABRICANTE_MUEBLES FOREIGN KEY(COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_COD_COCINA_MUEBLES FOREIGN KEY(COD_COCINA) REFERENCES COCINAS(COD_COCINA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS M_BAJOS(
COD_MUEBLE INT(11) PRIMARY KEY,
ALTURA DECIMAL(3,2) UNSIGNED NOT NULL,

CONSTRAINT FK_M_BAJOS_MUEBLES FOREIGN KEY(COD_MUEBLE) REFERENCES MUEBLES(COD_MUEBLE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ENCIMERAS(
COD_MUEBLE INT(11) PRIMARY KEY,
TIPO_ENCIMERA ENUM('M','S') NOT NULL,
CONSTRAINT FK_ENCIMERAS_MUEBLES FOREIGN KEY(COD_MUEBLE) REFERENCES MUEBLES(COD_MUEBLE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MONTA(
COD_MONTADOR INT(11) NOT NULL,
COD_COCINA INT(11) NOT NULL,
    
PRIMARY KEY (COD_MONTADOR, COD_COCINA),
CONSTRAINT FK_MONTA_MONTADORES FOREIGN KEY(COD_MONTADOR) REFERENCES MONTADORES(COD_MONTADOR) ON UPDATE CASCADE ON DELETE CASCADE, 
CONSTRAINT FK_MONTA_COCINAS FOREIGN KEY(COD_COCINA) REFERENCES COCINAS(COD_COCINA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TLFS_FABRICANTES(
COD_FABRICANTE INT(11) NOT NULL,
TLF CHAR(9) NOT NULL,
    
PRIMARY KEY(COD_FABRICANTE, TLF),
CONSTRAINT FK_TLFS_FABRICANTES FOREIGN KEY(COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CEDE(
COD_DISTRIBUIDOR_CEDE_COCINA INT(11) NOT NULL,
COD_COCINA_CEDIDA INT(11) NOT NULL,
COD_DISTRIBUIDOR_RECIBE_COCINA INT(11) NOT NULL,
    
PRIMARY KEY(COD_DISTRIBUIDOR_CEDE_COCINA, COD_COCINA_CEDIDA, COD_DISTRIBUIDOR_RECIBE_COCINA),
CONSTRAINT FK_CEDE_CEDE FOREIGN KEY(COD_DISTRIBUIDOR_CEDE_COCINA) REFERENCES DISTRIBUIDORES(COD_DISTRIBUIDOR) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_CEDE_COCINAS FOREIGN KEY(COD_COCINA_CEDIDA) REFERENCES COCINAS(COD_COCINA) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_CEDE_RECIBE FOREIGN KEY(COD_DISTRIBUIDOR_RECIBE_COCINA) REFERENCES DISTRIBUIDORES(COD_DISTRIBUIDOR) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRABAJA(
COD_FABRICANTE INT(11) NOT NULL,
COD_DISTRIBUIDOR INT(11) NOT NULL,
    
PRIMARY KEY(COD_FABRICANTE, COD_DISTRIBUIDOR),
CONSTRAINT FK_TRABAJA_FABRICANTES FOREIGN KEY(COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_TRABAJA_DISTRIBUIDORES FOREIGN KEY(COD_DISTRIBUIDOR) REFERENCES DISTRIBUIDORES(COD_DISTRIBUIDOR) ON UPDATE CASCADE ON DELETE CASCADE
);
