CREATE DATABASE IF NOT EXISTS ALOJAMIENTOS_RURALES;
USE ALOJAMIENTOS_RURALES;

CREATE TABLE IF NOT EXISTS ACTIVIDADES(
COD_ACTIVIDADES INT(11) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(300) NOT NULL,
NIVEL_DIFICULTAD TINYINT UNSIGNED,
CONSTRAINT CHK_NIVEL_DIFICULTAD_ACTIVIDADES CHECK(NIVEL_DIFICULTAD BETWEEN 0 AND 10)
);

CREATE TABLE IF NOT EXISTS ALOJAMIENTOS(
COD_ALOJAMIENTOS INT(11) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(300) NOT NULL UNIQUE,
TLF CHAR(9) NOT NULL,
COD_PERSONA_CONTACTO INT(11) NOT NULL,
CONSTRAINT UQ_NOMBRE_ALOJAMIENTOS UNIQUE(NOMBRE)
);

CREATE TABLE IF NOT EXISTS PERSONAL(
COD_PERSONAL INT(11) AUTO_INCREMENT PRIMARY KEY,
NIF CHAR(9) UNIQUE NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO_1 VARCHAR(100) NOT NULL,
APELLIDO_2 VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(150) NOT NULL,
TLF CHAR(9) NOT NULL,
COD_ALOJAMIENTOS INT(11) NOT NULL,
CONSTRAINT FK_COD_ALOJAMIENTOS_PERSONAL_ALOJAMIENTOS FOREIGN KEY(COD_ALOJAMIENTOS) REFERENCES ALOJAMIENTOS(COD_ALOJAMIENTOS) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HABITACIONES(
COD_HABITACIONES INT(11) AUTO_INCREMENT PRIMARY KEY,
PRECIO DECIMAL(5,2) UNSIGNED NOT NULL,
TIPO ENUM('I','D','T') NOT NULL,
BANIO ENUM('SI','NO') NOT NULL DEFAULT 'SI',
COD_ALOJAMIENTOS INT(11) NOT NULL,
CONSTRAINT FK_COD_ALOJAMIENTOS_HABITACIONES_ALOJAMIENTOS FOREIGN KEY(COD_ALOJAMIENTOS) REFERENCES ALOJAMIENTOS(COD_ALOJAMIENTOS) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ORGANIZAN(
COD_ACTIVIDADES INT(11),
COD_ALOJAMIENTOS INT(11),
FECHA DATE,
CONSTRAINT PK_ORGANIZAN PRIMARY KEY(COD_ACTIVIDADES, COD_ALOJAMIENTOS, FECHA),
CONSTRAINT FK_COD_ACTIVIDADES_ORGANIZAN_ALOJAMIENTOS FOREIGN KEY(COD_ACTIVIDADES) REFERENCES ACTIVIDADES(COD_ACTIVIDADES) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_COD_ALOJAMIENTOS_ORGANIZAN_ALOJAMIENTOS FOREIGN KEY(COD_ALOJAMIENTOS) REFERENCES ALOJAMIENTOS(COD_ALOJAMIENTOS) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE ALOJAMIENTOS ADD CONSTRAINT UQ_COD_PERSONA_CONTACTO_ALOJAMIENTOS UNIQUE(COD_PERSONA_CONTACTO);
ALTER TABLE ALOJAMIENTOS ADD CONSTRAINT FK_COD_PERSONA_CONTACTO_ALOJAMIENTOS_PERSONAL FOREIGN KEY(COD_PERSONA_CONTACTO) REFERENCES PERSONAL(COD_PERSONAL) ON UPDATE CASCADE ON DELETE RESTRICT;