-- EJERCICIO 2
/* HALLAR EL SALARIO MEDIO Y LA EDAD MEDIA EN AÑOS DE LOS EMPLEADOS QUE TIENEN COMISIÓN Y 
LOS QU ENO(CON UNA CABECERA QUE LOS DISTINGA, 
POR EJEMPLO: CON COMISIÓN, SIN COMISIÓN)). DEBE QUEDAR EXACTAMENTE ASÍ:
*/

-- MEDIA SALARIO EMPLEADOS CON COMISION

SELECT CURDATE() HOY, 'CON' AS'COMISION', 
       COUNT(*) TOTLA_EMPLEADOS,
       ROUND(AVG(SALARIO),2) SALARIO_MEDIO,
       ROUND(AVG(YEAR(CURDATE()) - YEAR(FECHA)),2) EDAD_MEDIA
FROM EMPLEADOS
WHERE COMISION IS NOT NULL
UNION
SELECT CURDATE() HOY, 'SIN' AS'COMISION', 
       COUNT(*) TOTLA_EMPLEADOS,
       ROUND(AVG(SALARIO),2) SALARIO_MEDIO,
       ROUND(AVG(YEAR(CURDATE()) - YEAR(FECHA)),2) EDAD_MEDIA
FROM EMPLEADOS
WHERE COMISION IS NOT NULL


-- EJERCICIO 3

/*
OBTENER LOS NOMBRE Y SALARIOS DE LOS EMPLEADOS CUYO SALARIO COUNDICE CON LA COMISION DE ALGUN OTRO PERO
NO CON LA SUYA PROPIA (CUIDADO QE HAY UN EMPLEADO CON EL MISMO SALAIO QUE COMISION, Y ESE NO DEBE SALIR
EN EL RESULTADO)
*/

SELECT NOMBRE, SALARIOS, EMPLEADOS
FROM EMPLEADOS E
WHERE E.SALARIO = ANY (SELECT COMISION
					   FROM EMPLEADOS
					   WHERE COMISION NOR LIKE E.COMISION)
ORDER BY 1;