CREATE DATABASE IF NOT EXISTS Boletin_1_Bancos CHARACTER SET utf8;

USE Boletin_1_Bancos;
SHOW CREATE DATABASE BOLETIN_1_BANCOS;
CREATE TABLE IF NOT EXISTS CATEGORIAS(
ID_CATEGORIA INT(11) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROVEEDORES(
ID_PROVEEDOR INT(11) AUTO_INCREMENT PRIMARY KEY,
DIRECCION VARCHAR(100) NOT NULL,
LOCALIDAD VARCHAR(100) NOT NULL,
PROVINCIA VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PIEZAS(
ID_PIEZAS INT(11) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
COLOR VARCHAR(15) NOT NULL DEFAULT "GRIS",
PRECIO DECIMAL(7,2) UNSIGNED NOT NULL,
ID_CATEGORIA INT(11) NOT NULL DEFAULT 999,
CONSTRAINT FK_ID_CATEGORIA_PIEZAS_CATEGORIAS FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
	ON UPDATE CASCADE ON DELETE SET NULL 
);
DROP TABLE IF EXISTS SUMINISTRA;
CREATE TABLE IF NOT EXISTS SUMINISTRA(
ID_PROVEEDOR INT(11),
ID_PIEZAS INT(11),
FECHA DATE,
CANTIDAD TINYINT UNSIGNED NOT NULL,
PRIMARY KEY (ID_PROVEEDOR,ID_PIEZAS,FECHA),
CONSTRAINT FK_ID_PROVEEDOR_SUMINISTRA_PROVEEDORES FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
	ON UPDATE CASCADE ON DELETE RESTRICT,
CONSTRAINT FK_ID_PIEZAS_SUMINISTRA_PIEZAS FOREIGN KEY(ID_PIEZA) REFERENCES PIEZAS(ID_PIEZA)
);