# COSULTA 3
SELECT *
FROM EMPLEADOS;

# CONSULTA 4
SELECT *
FROM EMPLEADOS
ORDER BY APELLIDO ASC;

# CONSULTA 7
SELECT *
FROM EMPLEADOS
WHERE SALARIO > 2000;

# CONSULTA 8
SELECT *
FROM EMPLEADOS
WHERE OFICIO LIKE 'ANALISTA';

# CONSULTA 12
SELECT *
FROM EMPLEADOS
WHERE DEP_NO = 10 AND OFICIO LIKE 'ANALISTA';

# CONSULTA 15
SELECT *
FROM EMPLEADOS
WHERE APELLIDO LIKE '%z'

# CONSULTA 17
SELECT *
FROM EMPLEADOS
WHERE APELLIDO LIKE 'A%' AND OFICIO LIKE '%E%';

# CONSULTA 24
SELECT APELLIDO
FROM EMPLEADOS
WHERE COMISION IS NULL;

# CONSULTA 26
SELECT *
FROM EMPLEADOS
WHERE OFICIO IN ('VENDEDOR', 'ANALISTA', 'EMPLEADO');

# CONSULTA 31
SELECT *, LOWER(APRELLIDO) MINUSCULA
FROM EMPLEADOS
