DROP DATABASE IF EXISTS HIPICA;
CREATE DATABASE IF NOT EXISTS HIPICA;
USE HIPICA;

CREATE TABLE IF NOT EXISTS CLIENTES(
DNI CHAR(9) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL
);

ALTER TABLE CLIENTES ADD COLUMN NACIONALIDAD VARCHAR(20);

CREATE TABLE IF NOT EXISTS CABALLOS(
COD_CABALLO CHAR(4) PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
PESO INT(3) CHECK (PESO BETWEEN 240 AND 300),
FECHA_NACIMIENTO DATE CHECK (FECHA_NACIMIENTO > '2000-01-01'),
PROPIETARIO VARCHAR(25) NOT NULL,
NACIONALIDAD VARCHAR(20) NOT NULL
);

ALTER TABLE CABALLOS ADD CONSTRAINT CHECK_NACIONALIDAD CHECK (NACIONALIDAD = LOWER(NACIONALIDAD) AND NACIONALIDAD IN('ESP', 'AR', 'BRI'));

CREATE TABLE IF NOT EXISTS CARRERAS(
COD_CARRERA CHAR(4) PRIMARY KEY,
FECHA_HORA DATETIME NOT NULL,
IMPORTE_PREMIO INT(6) NOT NULL,
APUESTA_LIMITE DECIMAL(7,2) NOT NULL DEFAULT 5 CHECK(APUESTA_LIMITE < 20000)
);

ALTER TABLE CARRERAS ADD CONSTRAINT CHECK_TEMPORADA CHECK (MONTH(FECHA_HORA) BETWEEN 3 AND 11);
ALTER TABLE CARRERAS ADD CONSTRAINT CHECK_HORARIO CHECK (HOUR(FECHA_HORA) BETWEEN 9 AND 14);

CREATE TABLE IF NOT EXISTS PARTICIPACIONES(
COD_CABALLO CHAR(4),
COD_CARRERA CHAR(4),
DORSAL INT(2) UNSIGNED NOT NULL,
JOCKEY VARCHAR(30) NOT NULL,
POSICION_FINAL INT(2) UNSIGNED NOT NULL CHECK (POSICION_FINAL > 0),

PRIMARY KEY(COD_CABALLO, COD_CARRERA),
CONSTRAINT FK_COD_CABALLO_PARTICIPACIONES_CABALLOS FOREIGN KEY(COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_COD_CARRERA_PARTICIPACIONES_CARRERAS FOREIGN KEY(COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE PARTICIPACIONES ADD CONSTRAINT CHECK_JOCKEY_MAYUS CHECK (JOCKEY = UPPER(JOCKEY));

CREATE TABLE IF NOT EXISTS APUESTAS(
DNI_CLIENTE CHAR(9),
COD_CABALLO CHAR(4),
COD_CARRERA CHAR(4) NOT NULL,
IMPORTE INT(6) NOT NULL DEFAULT 300 CHECK (IMPORTE > 0),
TANTOPORUNO DECIMAL(4,2) NOT NULL CHECK (TANTOPORUNO > 1),

PRIMARY KEY(DNI_CLIENTE, COD_CABALLO, COD_CARRERA),
CONSTRAINT FK_COD_CABALLO_APUESTAS_CABALLOS FOREIGN KEY(COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_COD_CARRERA_APUESTAS_CARRERAS FOREIGN KEY(COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA) ON UPDATE CASCADE ON DELETE CASCADE
);
